name: Deploy Javadoc to GitHub Pages (Maven)
on:
  release:
    types: [ published ]

jobs:
  generate-javadoc:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/gradle-generate-javadoc.yml@v1
    with:
      java-version: '17'
  deploy-javadoc:
    needs: [ generate-javadoc ]
    uses: Siroshun09/gh-actions-workflows/.github/workflows/deploy-to-gh-pages.yml@v1
    with:
      project-version: ${{ github.event.release.tag_name }}
      artifact-name: Javadoc
      update-latest: true
